#!/usr/bin/env bash

cd "$(dirname "$0")"/../../qcsrc/server/nadgets || exit 1
rm include.q*

tmp="$(mktemp)"
echo "// Autogenerated by extras/scripts/make-nadget-includes.sh" >> "$tmp"
echo >> "$tmp"
echo "#include \"nadgets.qh\"" >> "$tmp"
for i in *.qh; do
    [ "$i" == "nadgets.qh" ] && continue
    echo "#include \"$i\"" >> "$tmp"
done
mv "$tmp" "include.qh"

tmp="$(mktemp)"
echo "// Autogenerated by extras/scripts/make-nadget-includes.sh" >> "$tmp"
echo >> "$tmp"
for i in *.qc; do
    echo "#include \"$i\"" >> "$tmp"
done
mv "$tmp" "include.qc"
